# Generated by Django 4.1.2 on 2022-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', '-year'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gross_earning_in_mil',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rank',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=27, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Рейтинг Metascore'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(verbose_name='Год производства'),
        ),
    ]
