# Generated by Django 4.1.2 on 2022-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrities',
            name='biography',
            field=models.CharField(max_length=500, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='date',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='overview',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='masterpiece',
            field=models.CharField(max_length=500, null=True, verbose_name='Лучшие работы'),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='place',
            field=models.CharField(max_length=500, null=True, verbose_name='Страна'),
        ),
    ]
