# Generated by Django 4.1.2 on 2022-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_celebrities_biography_celebrities_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='date',
        ),
        migrations.AddField(
            model_name='celebrities',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
